##################################################################################
#                                                                                 
#   Conformance Pack:                                                             
#     Operational Best Practices for Monitoring                                  
#                                                                                 
#   This Conformance Pack has been designed for compatibility with the majority of 
#   AWS regions and to not require setting of any Parameters. Additional managed rules 
#   that require parameters to be set for your environment and/or for your specific 
#   region can be found at:
#   https://docs.aws.amazon.com/config/latest/developerguide/managed-rules-by-aws-config.html  
#                                                                                 
#   See Parameters section for names and descriptions of required parameters.       
#                                                                                 
##################################################################################

Parameters:
  DynamodbThroughputLimitCheckParamAccountRCUThresholdPercentage:
    Default: '80'
    Type: String
  DynamodbThroughputLimitCheckParamAccountWCUThresholdPercentage:
    Default: '80'
    Type: String
  GuarddutyNonArchivedFindingsParamDaysHighSev:
    Default: '1'
    Type: String
  GuarddutyNonArchivedFindingsParamDaysLowSev:
    Default: '30'
    Type: String
  GuarddutyNonArchivedFindingsParamDaysMediumSev:
    Default: '7'
    Type: String
  LambdaConcurrencyCheckParamConcurrencyLimitHigh:
    Default: '1000'
    Type: String
  LambdaConcurrencyCheckParamConcurrencyLimitLow:
    Default: '500'
    Type: String
Resources:
  AutoscalingGroupElbHealthcheckRequired:
    Properties:
      ConfigRuleName: autoscaling-group-elb-healthcheck-required
      Scope:
        ComplianceResourceTypes:
        - AWS::AutoScaling::AutoScalingGroup
      Source:
        Owner: AWS
        SourceIdentifier: AUTOSCALING_GROUP_ELB_HEALTHCHECK_REQUIRED
    Type: AWS::Config::ConfigRule
  CloudTrailCloudWatchLogsEnabled:
    Properties:
      ConfigRuleName: cloud-trail-cloud-watch-logs-enabled
      Source:
        Owner: AWS
        SourceIdentifier: CLOUD_TRAIL_CLOUD_WATCH_LOGS_ENABLED
    Type: AWS::Config::ConfigRule
  CloudwatchAlarmActionCheck:
    Properties:
      ConfigRuleName: cloudwatch-alarm-action-check
      InputParameters:
        alarmActionRequired: 'TRUE'
        insufficientDataActionRequired: 'TRUE'
        okActionRequired: 'FALSE'
      Scope:
        ComplianceResourceTypes:
        - AWS::CloudWatch::Alarm
      Source:
        Owner: AWS
        SourceIdentifier: CLOUDWATCH_ALARM_ACTION_CHECK
    Type: AWS::Config::ConfigRule
  DynamodbThroughputLimitCheck:
    Properties:
      ConfigRuleName: dynamodb-throughput-limit-check
      InputParameters:
        accountRCUThresholdPercentage:
          Fn::If:
          - dynamodbThroughputLimitCheckParamAccountRCUThresholdPercentage
          - Ref: DynamodbThroughputLimitCheckParamAccountRCUThresholdPercentage
          - Ref: AWS::NoValue
        accountWCUThresholdPercentage:
          Fn::If:
          - dynamodbThroughputLimitCheckParamAccountWCUThresholdPercentage
          - Ref: DynamodbThroughputLimitCheckParamAccountWCUThresholdPercentage
          - Ref: AWS::NoValue
      Source:
        Owner: AWS
        SourceIdentifier: DYNAMODB_THROUGHPUT_LIMIT_CHECK
    Type: AWS::Config::ConfigRule
  Ec2InstanceDetailedMonitoringEnabled:
    Properties:
      ConfigRuleName: ec2-instance-detailed-monitoring-enabled
      Scope:
        ComplianceResourceTypes:
        - AWS::EC2::Instance
      Source:
        Owner: AWS
        SourceIdentifier: EC2_INSTANCE_DETAILED_MONITORING_ENABLED
    Type: AWS::Config::ConfigRule
  GuarddutyEnabledCentralized:
    Properties:
      ConfigRuleName: guardduty-enabled-centralized
      Source:
        Owner: AWS
        SourceIdentifier: GUARDDUTY_ENABLED_CENTRALIZED
    Type: AWS::Config::ConfigRule
  GuarddutyNonArchivedFindings:
    Properties:
      ConfigRuleName: guardduty-non-archived-findings
      InputParameters:
        daysHighSev:
          Fn::If:
          - guarddutyNonArchivedFindingsParamDaysHighSev
          - Ref: GuarddutyNonArchivedFindingsParamDaysHighSev
          - Ref: AWS::NoValue
        daysLowSev:
          Fn::If:
          - guarddutyNonArchivedFindingsParamDaysLowSev
          - Ref: GuarddutyNonArchivedFindingsParamDaysLowSev
          - Ref: AWS::NoValue
        daysMediumSev:
          Fn::If:
          - guarddutyNonArchivedFindingsParamDaysMediumSev
          - Ref: GuarddutyNonArchivedFindingsParamDaysMediumSev
          - Ref: AWS::NoValue
      Source:
        Owner: AWS
        SourceIdentifier: GUARDDUTY_NON_ARCHIVED_FINDINGS
    Type: AWS::Config::ConfigRule
  LambdaConcurrencyCheck:
    Properties:
      ConfigRuleName: lambda-concurrency-check
      InputParameters:
        ConcurrencyLimitHigh:
          Fn::If:
          - lambdaConcurrencyCheckParamConcurrencyLimitHigh
          - Ref: LambdaConcurrencyCheckParamConcurrencyLimitHigh
          - Ref: AWS::NoValue
        ConcurrencyLimitLow:
          Fn::If:
          - lambdaConcurrencyCheckParamConcurrencyLimitLow
          - Ref: LambdaConcurrencyCheckParamConcurrencyLimitLow
          - Ref: AWS::NoValue
      Scope:
        ComplianceResourceTypes:
        - AWS::Lambda::Function
      Source:
        Owner: AWS
        SourceIdentifier: LAMBDA_CONCURRENCY_CHECK
    Type: AWS::Config::ConfigRule
  LambdaDlqCheck:
    Properties:
      ConfigRuleName: lambda-dlq-check
      Scope:
        ComplianceResourceTypes:
        - AWS::Lambda::Function
      Source:
        Owner: AWS
        SourceIdentifier: LAMBDA_DLQ_CHECK
    Type: AWS::Config::ConfigRule
  RdsEnhancedMonitoringEnabled:
    Properties:
      ConfigRuleName: rds-enhanced-monitoring-enabled
      Scope:
        ComplianceResourceTypes:
        - AWS::RDS::DBInstance
      Source:
        Owner: AWS
        SourceIdentifier: RDS_ENHANCED_MONITORING_ENABLED
    Type: AWS::Config::ConfigRule
  SecurityhubEnabled:
    Properties:
      ConfigRuleName: securityhub-enabled
      Source:
        Owner: AWS
        SourceIdentifier: SECURITYHUB_ENABLED
    Type: AWS::Config::ConfigRule
Conditions:
  dynamodbThroughputLimitCheckParamAccountRCUThresholdPercentage:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: DynamodbThroughputLimitCheckParamAccountRCUThresholdPercentage
  dynamodbThroughputLimitCheckParamAccountWCUThresholdPercentage:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: DynamodbThroughputLimitCheckParamAccountWCUThresholdPercentage
  guarddutyNonArchivedFindingsParamDaysHighSev:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: GuarddutyNonArchivedFindingsParamDaysHighSev
  guarddutyNonArchivedFindingsParamDaysLowSev:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: GuarddutyNonArchivedFindingsParamDaysLowSev
  guarddutyNonArchivedFindingsParamDaysMediumSev:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: GuarddutyNonArchivedFindingsParamDaysMediumSev
  lambdaConcurrencyCheckParamConcurrencyLimitHigh:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: LambdaConcurrencyCheckParamConcurrencyLimitHigh
  lambdaConcurrencyCheckParamConcurrencyLimitLow:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: LambdaConcurrencyCheckParamConcurrencyLimitLow
